{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_request_duration_seconds_sum{endpoint!=\"/metrics\", endpoint!=\"/favicon.ico\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "app_requests_total{endpoint!=\"/metrics\", endpoint!=\"/favicon.ico\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(app_requests_total{endpoint!=\"/metrics\", endpoint!=\"/favicon.ico\"}[5m])",
     "legendFormat": "{{method}} {{endpoint}}"
    },
    {}
   ]
  }
 ]
}